(
    WAIT_FOR_USERNAME,
    MAIN_MENU, TOP_10, RULES,
    TASK_CHOOSING, TASK_SHOWN, ANSWERING,
    ANSWER_RIGHT, ANSWER_WRONG,

    ADMIN_MENU, ADMIN_TASK_CHOOSE_PUBLISH, ADMIN_TASK_CHOOSE_HIDE,
    ADMIN_TASK_PUBLISHED,
    ADMIN_ACCESS_DENIED,
    *_
) = range(100)
